### ISSUE TITLE
Why need to set sensitivity?

### ISSUE THREAD

**Issue by GanZhiXiong** [rezigned/Mousemory#1]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/27394631/183570168-29f7563a-d84a-4be0-8ec4-d57568b7f244.png">

**Comment by rezigned** [comment]
Hi @GanZhiXiong, in some situation, the other apps might take too long to become active and Mousemory can't capture that (because macOS doesn't notify us). So, the delay here is just an optimal time to wait for those situations.

**Comment by GanZhiXiong** [comment]
I'm very interested in this app, it's doing great 👍🏻!

Can you list the situations in which a delay is required? I haven't found a problem so far.

I look forward to contributing to this project.

**Comment by rezigned** [comment]
> I'm very interested in this app, it's doing great 👍🏻!
> 
> Can you list the situations in which a delay is required? I haven't found a problem so far.
> 
> I look forward to contributing to this project.

If i remember correctly. It only happened to certain apps (e.g. LINE chat).

Glad to hear that it's useful for you and your contributions are welcome :)

**Comment by GanZhiXiong** [comment]
Ok, I will try
